# Optional S3-linked FSx for Lustre mounted at /data (R7, KTD7).
#
# TOGGLE WARNINGS (R10):
#   - Disabling enable_fsx on a live deployment DESTROYS the file system.
#     Auto-export to S3 is asynchronous — verify the DRA export has caught up
#     before flipping the flag (see docs/runbooks.md).
#   - Enabling FSx after instances are already running does NOT mount /data on
#     them: user_data runs once at first boot and is ignored after creation
#     (lifecycle ignore_changes, deliberate — see instance.tf), so the flip
#     changes nothing on running instances. Mount manually per the runbook
#     (the fsx_manual_mount_command output is the exact command), or launch
#     FSx before the instances.
#   - FSx bills continuously from creation — including before the capacity
#     block starts, which is the point of pre-loading (KTD9) but is real spend.

resource "aws_fsx_lustre_file_system" "data" {
  count = var.enable_fsx ? 1 : 0

  # PERSISTENT_2 is the only deployment type supporting DRA auto-export
  # (KTD7); the legacy import_path/export_path arguments are unsupported on
  # it, hence the separate association resource below. storage_type defaults
  # to SSD, the only option for PERSISTENT_2.
  deployment_type             = "PERSISTENT_2"
  storage_capacity            = var.fsx_storage_capacity_gib
  per_unit_storage_throughput = var.fsx_per_unit_throughput

  # Same subnet and SG as the instances: the SG already carries the
  # self-referencing Lustre rules (TCP 988, 1018-1023) from security.tf.
  subnet_ids         = [aws_subnet.public.id]
  security_group_ids = [aws_security_group.gpu.id]

  tags = merge(local.tags, { Name = "${local.name_prefix}-data" })
}

# Links the file system root to the operator's S3 bucket. The bucket must be
# in the same region as the capacity block — a wrong-region bucket fails at
# DRA creation, after FSx has already started billing.
resource "aws_fsx_data_repository_association" "s3" {
  count = var.enable_fsx ? 1 : 0

  file_system_id       = aws_fsx_lustre_file_system.data[0].id
  data_repository_path = "s3://${var.fsx_s3_bucket}"
  file_system_path     = "/"

  # Import the bucket's existing metadata up front so /data lists the whole
  # bucket immediately (file contents still lazy-load on first read).
  batch_import_meta_data_on_create = true

  s3 {
    auto_import_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }

    # Import-only when fsx_auto_export = false — for read-only training
    # buckets that must never be written back to (KTD7).
    dynamic "auto_export_policy" {
      for_each = var.fsx_auto_export ? [true] : []

      content {
        events = ["NEW", "CHANGED", "DELETED"]
      }
    }
  }
}

locals {
  # Total (never-erroring) forms of the file system's generated endpoints:
  # empty string while FSx is disabled, the real values (unknown until apply)
  # while enabled. mount_name is generated by AWS — never hardcode it.
  fsx_dns_name   = join("", aws_fsx_lustre_file_system.data[*].dns_name)
  fsx_mount_name = join("", aws_fsx_lustre_file_system.data[*].mount_name)

  # Bash fragment for the enabled case. Built from the total locals above so
  # it evaluates cleanly in every configuration; only fsx_mount_snippet below
  # decides whether it reaches the instances.
  fsx_mount_fragment = <<-EOT
    # --- FSx for Lustre mount at /data (R7) ------------------------------------
    # Install the Lustre client matching the OS generation. A failed install
    # FAILS LOUDLY (nonzero exit, message in the console log) — silently
    # skipping the mount would quietly divorce /data from S3.
    . /etc/os-release
    if [ "$${ID:-}" = "amzn" ] && [ "$${VERSION_ID:-}" = "2" ]; then
      amazon-linux-extras install -y lustre \
        || { echo "FATAL: Lustre client install failed (AL2); /data will NOT be mounted" >&2; exit 1; }
    elif [ "$${ID:-}" = "amzn" ] && [ "$${VERSION_ID:-}" = "2023" ]; then
      dnf install -y lustre-client \
        || { echo "FATAL: Lustre client install failed (AL2023); /data will NOT be mounted" >&2; exit 1; }
    else
      echo "FATAL: unrecognized OS ($${PRETTY_NAME:-unknown}); cannot pick a Lustre client package, /data will NOT be mounted" >&2
      exit 1
    fi

    mkdir -p /data
    # Immutable while unmounted: if the mount below fails, writes to the decoy
    # root-volume directory fail with EPERM instead of quietly producing
    # checkpoints that die with the root volume. Mounting Lustre OVER the
    # immutable mountpoint still works. Skipped when /data is already a live
    # mount (idempotent manual re-run), where chattr may not apply.
    findmnt /data >/dev/null || chattr +i /data

    # _netdev is MANDATORY: without it the instance can hang at boot waiting
    # for Lustre before the network is up. x-systemd.automount re-mounts on
    # first access after any reboot.
    fstab_line="${local.fsx_dns_name}@tcp:/${local.fsx_mount_name} /data lustre defaults,relatime,flock,_netdev,x-systemd.automount 0 0"
    grep -qxF "$fstab_line" /etc/fstab || echo "$fstab_line" >>/etc/fstab

    # mount -a alone is not the gate: under set -e its failure would abort
    # before the diagnostics below could run. findmnt is the authoritative
    # check that /data really is the Lustre file system.
    mount -a || true

    if findmnt -t lustre /data >/dev/null; then
      # Clear any stale marker left by a previously failed attempt.
      rm -f /etc/profile.d/00-fsx-broken.sh
    else
      # The instance stays SSH-healthy with /data as an empty immutable
      # directory — leave a login-visible warning so nobody trusts the decoy.
      # user_data runs as root: /etc/profile.d is writable directly, no sudo.
      echo 'echo "WARNING: /data is NOT mounted - do not write checkpoints locally; see cloud-init logs (/var/log/cloud-init-output.log)"' >/etc/profile.d/00-fsx-broken.sh
      chmod 0644 /etc/profile.d/00-fsx-broken.sh
      echo "FATAL: /data is not a mounted Lustre file system after mount -a; see errors above" >&2
      exit 1
    fi
  EOT

  # The user_data seam declared in instance.tf, owned here from U5 on. Empty
  # when FSx is disabled so the rendered user_data carries no Lustre content
  # at all.
  fsx_mount_snippet = var.enable_fsx ? local.fsx_mount_fragment : ""
}
